# Generated by Django 4.2 on 2023-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='recommended_books',
            field=models.BooleanField(default=True),
        ),
    ]
