# Generated by Django 4.2 on 2023-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
